### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by stefan-niedermann** [justincavery/am-i-responsive#15]
Dear @justincavery,

i really like thiss webapp, it is still useful to generate beautiful screenshots.

Could you please add a LICENSE-file or a statement in the README und which license you published the source code?

If you do not know which to choose, let me recommend GPLv3+, this will ensure that every enhancement will be free and open source, too.

I would like to reuse some parts for a own project, but a missing license is currently a legal issue :-(

Regards

**Comment by stefan-niedermann** [comment]
ping @justincavery

**Comment by hentrev** [comment]
+1

**Comment by justincavery** [comment]
Thanks @stefan-niedermann for the initial request and ping, and @hentrev for the final nail.  MIT license applied.

**Comment by stefan-niedermann** [comment]
Thank you @justincavery :) Does this license also apply to the images?

**Comment by hentrev** [comment]
Thanks @justincavery! Cool project :)

**Comment by justincavery** [comment]
> Thank you @justincavery :) Does this license also apply to the images?

@stefan-niedermann the images that you create as a result of using the tool are covered by the license, but the images on the devices themselves were purchased under different license and are only covered for use of the tool.
