### ISSUE TITLE
Website link redirecting to website

### ISSUE THREAD

**Issue by SmarterWebsites** [justincavery/am-i-responsive#18]
Hey Guys,

When you input a URL into the search bar and click on Go! it sends us through to the website that we put into the search bar.
It will preview the iamresponsive screenshot but only for about .1 seconds then sends us through to the website.

Wondering if you guys can fix this ASAP.

**Comment by justincavery** [comment]
@SmarterWebsites sorry for the long delay.

A few sites do this and I'm not 100% sure why.  There are a few problems with this method as it relies on the site being previewed allowing our tool to iframe the site into the page.  You might notice you get a warning with some sites telling you that X-Frame-Options are denied... this is one problem.

I assume the redirection is part of the same issue, I originally came across it when trying to view mint.com in the tool.
